{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "commerce.serviceAccountName" . }}
  labels:
{{ include "commerce.labels" . | indent 4 }}
{{- end -}}
